/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as VoiceAgentIdRouteImport } from './routes/voice.$agentId'
import { Route as SolutionsKidneyCareRouteImport } from './routes/solutions.kidney-care'
import { Route as ConsoleNumbersRouteImport } from './routes/console.numbers'
import { Route as ConsoleLiveRouteImport } from './routes/console.live'
import { Route as ConsoleKeysRouteImport } from './routes/console.keys'
import { Route as ConsoleDashboardRouteImport } from './routes/console.dashboard'
import { Route as ConsoleConversationsRouteImport } from './routes/console.conversations'
import { Route as ConsoleAnalyticsRouteImport } from './routes/console.analytics'
import { Route as ConsoleAgentsRouteImport } from './routes/console.agents'
import { Route as AgentsCreateRouteImport } from './routes/agents.create'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const VoiceAgentIdRoute = VoiceAgentIdRouteImport.update({
  id: '/voice/$agentId',
  path: '/voice/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsKidneyCareRoute = SolutionsKidneyCareRouteImport.update({
  id: '/kidney-care',
  path: '/kidney-care',
  getParentRoute: () => SolutionsRoute,
} as any)
const ConsoleNumbersRoute = ConsoleNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleLiveRoute = ConsoleLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleKeysRoute = ConsoleKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDashboardRoute = ConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleConversationsRoute = ConsoleConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAnalyticsRoute = ConsoleAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAgentsRoute = ConsoleAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ConsoleRoute,
} as any)
const AgentsCreateRoute = AgentsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/console': typeof ConsoleRouteWithChildren
  '/conversations': typeof ConversationsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/showcase': typeof ShowcaseRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/create': typeof AgentsCreateRoute
  '/console/agents': typeof ConsoleAgentsRoute
  '/console/analytics': typeof ConsoleAnalyticsRoute
  '/console/conversations': typeof ConsoleConversationsRoute
  '/console/dashboard': typeof ConsoleDashboardRoute
  '/console/keys': typeof ConsoleKeysRoute
  '/console/live': typeof ConsoleLiveRoute
  '/console/numbers': typeof ConsoleNumbersRoute
  '/solutions/kidney-care': typeof SolutionsKidneyCareRoute
  '/voice/$agentId': typeof VoiceAgentIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/showcase': typeof ShowcaseRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/create': typeof AgentsCreateRoute
  '/console/agents': typeof ConsoleAgentsRoute
  '/console/analytics': typeof ConsoleAnalyticsRoute
  '/console/conversations': typeof ConsoleConversationsRoute
  '/console/dashboard': typeof ConsoleDashboardRoute
  '/console/keys': typeof ConsoleKeysRoute
  '/console/live': typeof ConsoleLiveRoute
  '/console/numbers': typeof ConsoleNumbersRoute
  '/solutions/kidney-care': typeof SolutionsKidneyCareRoute
  '/voice/$agentId': typeof VoiceAgentIdRoute
  '/agents': typeof AgentsIndexRoute
  '/console': typeof ConsoleIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/console': typeof ConsoleRouteWithChildren
  '/conversations': typeof ConversationsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/showcase': typeof ShowcaseRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/create': typeof AgentsCreateRoute
  '/console/agents': typeof ConsoleAgentsRoute
  '/console/analytics': typeof ConsoleAnalyticsRoute
  '/console/conversations': typeof ConsoleConversationsRoute
  '/console/dashboard': typeof ConsoleDashboardRoute
  '/console/keys': typeof ConsoleKeysRoute
  '/console/live': typeof ConsoleLiveRoute
  '/console/numbers': typeof ConsoleNumbersRoute
  '/solutions/kidney-care': typeof SolutionsKidneyCareRoute
  '/voice/$agentId': typeof VoiceAgentIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/console'
    | '/conversations'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/showcase'
    | '/solutions'
    | '/agents/$agentId'
    | '/agents/create'
    | '/console/agents'
    | '/console/analytics'
    | '/console/conversations'
    | '/console/dashboard'
    | '/console/keys'
    | '/console/live'
    | '/console/numbers'
    | '/solutions/kidney-care'
    | '/voice/$agentId'
    | '/agents/'
    | '/console/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/showcase'
    | '/agents/$agentId'
    | '/agents/create'
    | '/console/agents'
    | '/console/analytics'
    | '/console/conversations'
    | '/console/dashboard'
    | '/console/keys'
    | '/console/live'
    | '/console/numbers'
    | '/solutions/kidney-care'
    | '/voice/$agentId'
    | '/agents'
    | '/console'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/console'
    | '/conversations'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/showcase'
    | '/solutions'
    | '/agents/$agentId'
    | '/agents/create'
    | '/console/agents'
    | '/console/analytics'
    | '/console/conversations'
    | '/console/dashboard'
    | '/console/keys'
    | '/console/live'
    | '/console/numbers'
    | '/solutions/kidney-care'
    | '/voice/$agentId'
    | '/agents/'
    | '/console/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ConsoleRoute: typeof ConsoleRouteWithChildren
  ConversationsRoute: typeof ConversationsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ShowcaseRoute: typeof ShowcaseRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  VoiceAgentIdRoute: typeof VoiceAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/voice/$agentId': {
      id: '/voice/$agentId'
      path: '/voice/$agentId'
      fullPath: '/voice/$agentId'
      preLoaderRoute: typeof VoiceAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/kidney-care': {
      id: '/solutions/kidney-care'
      path: '/kidney-care'
      fullPath: '/solutions/kidney-care'
      preLoaderRoute: typeof SolutionsKidneyCareRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/console/numbers': {
      id: '/console/numbers'
      path: '/numbers'
      fullPath: '/console/numbers'
      preLoaderRoute: typeof ConsoleNumbersRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/live': {
      id: '/console/live'
      path: '/live'
      fullPath: '/console/live'
      preLoaderRoute: typeof ConsoleLiveRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/keys': {
      id: '/console/keys'
      path: '/keys'
      fullPath: '/console/keys'
      preLoaderRoute: typeof ConsoleKeysRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/dashboard': {
      id: '/console/dashboard'
      path: '/dashboard'
      fullPath: '/console/dashboard'
      preLoaderRoute: typeof ConsoleDashboardRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/conversations': {
      id: '/console/conversations'
      path: '/conversations'
      fullPath: '/console/conversations'
      preLoaderRoute: typeof ConsoleConversationsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/analytics': {
      id: '/console/analytics'
      path: '/analytics'
      fullPath: '/console/analytics'
      preLoaderRoute: typeof ConsoleAnalyticsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/agents': {
      id: '/console/agents'
      path: '/agents'
      fullPath: '/console/agents'
      preLoaderRoute: typeof ConsoleAgentsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/agents/create': {
      id: '/agents/create'
      path: '/create'
      fullPath: '/agents/create'
      preLoaderRoute: typeof AgentsCreateRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsCreateRoute: typeof AgentsCreateRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsCreateRoute: AgentsCreateRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface ConsoleRouteChildren {
  ConsoleAgentsRoute: typeof ConsoleAgentsRoute
  ConsoleAnalyticsRoute: typeof ConsoleAnalyticsRoute
  ConsoleConversationsRoute: typeof ConsoleConversationsRoute
  ConsoleDashboardRoute: typeof ConsoleDashboardRoute
  ConsoleKeysRoute: typeof ConsoleKeysRoute
  ConsoleLiveRoute: typeof ConsoleLiveRoute
  ConsoleNumbersRoute: typeof ConsoleNumbersRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAgentsRoute: ConsoleAgentsRoute,
  ConsoleAnalyticsRoute: ConsoleAnalyticsRoute,
  ConsoleConversationsRoute: ConsoleConversationsRoute,
  ConsoleDashboardRoute: ConsoleDashboardRoute,
  ConsoleKeysRoute: ConsoleKeysRoute,
  ConsoleLiveRoute: ConsoleLiveRoute,
  ConsoleNumbersRoute: ConsoleNumbersRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface SolutionsRouteChildren {
  SolutionsKidneyCareRoute: typeof SolutionsKidneyCareRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsKidneyCareRoute: SolutionsKidneyCareRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ConsoleRoute: ConsoleRouteWithChildren,
  ConversationsRoute: ConversationsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ShowcaseRoute: ShowcaseRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  VoiceAgentIdRoute: VoiceAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
